config/routes.rb
Rails.application.routes.draw do

  get 'index/index'
 

  devise_for :users

    resources :users
    resources :workers
    resources :locations
    resources :instruments
    resources :investments
    resources :expenditures
    resources :salaries
    resources :customers
    resources :work_types
    resources :location_work_types
    resources :location_customers
    resources :diaries
    resources :transports
    resources :materials
    resources :location_materials
    resources :payouts

    root "index#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :location_customers
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :location_work_type
	belongs_to :worker
	belongs_to :salary
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	belongs_to :location
	belongs_to :worker
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :instruments
	has_many :location_customers
	has_many :location_work_types
  	has_many :work_types, through: :location_work_types
  	has_many :location_materials
  	has_many :materials, through: :location_materials
end

app/models/material.rb
class Material < ApplicationRecord
	has_many :location_materials
	has_many :locations, through: :location_materials
end

app/models/payout.rb
class Payout < ApplicationRecord
	belongs_to :location_work_type
end

app/models/salary.rb
class Salary < ApplicationRecord
	belongs_to :worker
	has_many :diaries
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/work_type.rb
class WorkType < ApplicationRecord
	has_many :location_work_types
	has_many :locations, through: :location_work_types
end

app/models/worker.rb
class Worker < ApplicationRecord
	has_many :instruments
	has_many :salaries
	has_many :diaries
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  def show
    @transport = Transport.find(params[:id])
  end

  def index
    @transports = Transport.all
  end

  def new
    @transport = Transport.new
  end

  def create
    @transport = Transport.new(permit_params)
    @transport.save
    redirect_to(root_path)
  end

  def delete
  end

  def destroy
  end

  def edit
    @transport = Transport.find(params[:id])
  end

  def update
    @transport = Transport.find(params[:id])
    @transport.update(permit_params)
    redirect_to(transports_path)
  end

  private

  def permit_params
    params.require(:transport).permit(:name, :description, :price, :buy_date, :to_date, :insurance_date)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/payouts_helper.rb
module PayoutsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/transports/create.html.erb
<h1>Transports#create</h1>
<p>Find me in app/views/transports/create.html.erb</p>

app/views/transports/delete.html.erb
<h1>Transports#delete</h1>
<p>Find me in app/views/transports/delete.html.erb</p>

app/views/transports/destroy.html.erb
<h1>Transports#destroy</h1>
<p>Find me in app/views/transports/destroy.html.erb</p>

app/views/transports/edit.html.erb
<h1>Редактирование <%= @transport.name %></h1>

<%= form_for @transport do |f| %>
	<%= f.label :name, 'Название транспорта', class: "form-label" %>
	<%= f.text_field :name, class: "form-control", default: @transport.name %>
	<br>
	<%= f.label :description, 'Модель транспорта', class: "form-label" %>
	<%= f.text_field :description, class: "form-control", default: @transport.description %>
	<br>
	<%= f.label :price, 'Цена', class: "form-label" %>
	<%= f.text_field :price, class: "form-control", default: @transport.price %>
	<br>
	<%= f.label :buy_date, 'Дата покупки', class: "form-label" %>
	<%= f.date_field :buy_date, :id => "datepicker", class: "form-control", default: @transport.buy_date %>
	<br>
	<%= f.label :to_date, 'Дата последнего ТО (дд.мм.гггг)', class: "form-label" %>
	<%= f.date_field :to_date, :id => "datepicker", class: "form-control", default: @transport.to_date %>
	<br>
	<%= f.label :insurance_date, 'До когда действует страховка (дд.мм.гггг)', class: "form-label" %>
	<%= f.date_field :insurance_date, :id => "datepicker", class: "form-control", default: @transport.insurance_date %>
	<br>
	

	<%= f.submit 'Внести изменения', class: "btn btn-primary" %>
<% end %>

app/views/transports/index.html.erb
<h1>Транспорт <%= link_to "Добавить новый Транспорт", new_transport_path, class: "btn btn-primary" %> </h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название</th>
      <th scope="col">Модель</th>
      <th scope="col">Дата покупки</th>
      <th scope="col">Цена</th>
      <th scope="col">Страховка до</th>
      <th scope="col">Дата ТО</th>
      <th scope="col">Подробнее</th>
    </tr>
  </thead>
  <tbody>
	<% @transports.each do |transport| %>
    <tr>
      <th scope="row"><%= transport.id %></th>
      <td><%= transport.name %></td>
      <td><%= transport.description %></td>
      <td><%= transport.buy_date %></td>
      <td><%= transport.price %> zl</td>
      <td><%= transport.insurance_date %></td>
      <td><%= transport.to_date %></td>
      <td><%= link_to "Подробнее", "transports/#{transport.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/transports/new.html.erb
<h1>Добавление нового транспорта</h1>

<%= form_for @transport do |f| %>
	<%= f.label :name, 'Название транспорта', class: "form-label" %>
	<%= f.text_field :name, class: "form-control" %>
	<br>
	<%= f.label :description, 'Модель транспорта', class: "form-label" %>
	<%= f.text_field :description, class: "form-control" %>
	<br>
	<%= f.label :price, 'Цена', class: "form-label" %>
	<%= f.text_field :price, class: "form-control" %>
	<br>
	<%= f.label :buy_date, 'Дата покупки', class: "form-label" %>
	<%= f.date_field :buy_date, :id => "datepicker", class: "form-control" %>
	<br>
	<%= f.label :to_date, 'Дата последнего ТО (дд.мм.гггг)', class: "form-label" %>
	<%= f.date_field :to_date, :id => "datepicker", class: "form-control" %>
	<br>
	<%= f.label :insurance_date, 'До когда действует страховка (дд.мм.гггг)', class: "form-label" %>
	<%= f.date_field :insurance_date, :id => "datepicker", class: "form-control" %>
	<br>
	

	<%= f.submit 'Добавить', class: "btn btn-primary" %>
<% end %>

app/views/transports/show.html.erb
<h1>Транспорт <%= @transport.name %></h1>

<p>Имя: <%= @transport.name %></p>
<p>Модель: <%= @transport.description %></p>
<p>Цена: <%= @transport.price %>zl</p>
<p>Дата покупки: <%= @transport.buy_date %></p>
<p>Дата последнего ТО: <%= @transport.to_date %></p>
<p>Дата конца страховки: <%= @transport.insurance_date %></p>

<%= link_to "Редактировать", "#{@transport.id}/edit", class: "btn btn-primary" %>

app/views/transports/update.html.erb
<h1>Transports#update</h1>
<p>Find me in app/views/transports/update.html.erb</p>