config/routes.rb
Rails.application.routes.draw do

  get 'index/index'
 

  devise_for :users

    resources :users
    resources :workers
    resources :locations
    resources :instruments
    resources :investments
    resources :expenditures
    resources :salaries
    resources :customers
    resources :work_types
    resources :location_work_types
    resources :location_customers
    resources :diaries
    resources :transports
    resources :materials
    resources :location_materials
    resources :payouts

    root "index#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :location_customers
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :location_work_type
	belongs_to :worker
	belongs_to :salary
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	belongs_to :location
	belongs_to :worker
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :instruments
	has_many :location_customers
	has_many :location_work_types
  	has_many :work_types, through: :location_work_types
  	has_many :location_materials
  	has_many :materials, through: :location_materials
end

app/models/material.rb
class Material < ApplicationRecord
	has_many :location_materials
	has_many :locations, through: :location_materials
end

app/models/payout.rb
class Payout < ApplicationRecord
	belongs_to :location_work_type
end

app/models/salary.rb
class Salary < ApplicationRecord
	belongs_to :worker
	has_many :diaries
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/work_type.rb
class WorkType < ApplicationRecord
	has_many :location_work_types
	has_many :locations, through: :location_work_types
end

app/models/worker.rb
class Worker < ApplicationRecord
	has_many :instruments
	has_many :salaries
	has_many :diaries
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/payouts_helper.rb
module PayoutsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/index/index.html.erb
<h1 class="text-center">ГЛАВНАЯ</h1>
	

<% if @budget > 0%>
	<h4 class="text-center" style="color: green">Касса: +<strong name="kassa"><%= @budget %></strong> злотых</h4>
<% else %>
	<h4 class="text-center" style="color: red">Касса: <strong name="kassa"><%= @budget %></strong> злотых</h4>
<% end %>



<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        Оплаты работы заказчиками
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">id Оплаты</th>
      <th scope="col">Сумма</th>
      <th scope="col">Дата</th>
      <th scope="col">За что</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @dohods.sort_by{ |obj| obj.payout_date }.reverse.each do |payout| %>
    <tr>
      <th scope="row"><%= payout.id %></th>
      <td style="color: green" name="+money"> +<%= payout.size %> zl </td>
      <td name="date"> <%= payout.payout_date %> </td>
      <td> <%= payout.location_work_type.work_type.name %> на обьекте <%= payout.location_work_type.location.name %> </td>
    </tr>
     <% end %>
  </tbody>
</table>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        Зарплаты работникам
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">id Зарплаты</th>
      <th scope="col">Сумма</th>
      <th scope="col">Дата</th>
      <th scope="col">Кому</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @rashods[:salaries].sort_by{ |obj| obj.salary_date }.reverse.each do |salary|%>
    <tr>
      <th scope="row"><%= salary.id %></th>
      <td style="color: red" name="money"> -<%= salary.size %> zl </td>
      <td name="date"> <%= salary.salary_date %> </td>
      <td> <%= salary.worker.name %> </td>
    </tr>
     <% end %>
  </tbody>
</table>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        Закупки материалов
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">id Закупки</th>
      <th scope="col">Сумма</th>
      <th scope="col">Дата</th>
      <th scope="col">Материал</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @rashods[:materials].sort_by{ |obj| obj.buy_date }.reverse.each do |loc_material|%>
    <tr>
      <th scope="row"><%= loc_material.id %></th>
      <td style="color: red" name="money"> -<%= loc_material.price*loc_material.count %> zl </td>
      <td name="date"> <%= loc_material.buy_date %> </td>
      <td> <%= loc_material.count %> <%= loc_material.material.dimension %> <%= loc_material.material.name %> на <%= loc_material.location.name %> </td>
    </tr>
     <% end %>
  </tbody>
</table>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">
        Закупки инстурментов
      </button>
    </h2>
    <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingFour">
      <div class="accordion-body">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">id инструмента</th>
      <th scope="col">Сумма</th>
      <th scope="col">Дата</th>
      <th scope="col">Инструмент</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @rashods[:instruments].sort_by{ |obj| obj.buy_date }.reverse.each do |instrument|%>
    <tr>
      <th scope="row"><%= instrument.id %></th>
      <td style="color: red" name="money"> -<%= instrument.price %> zl </td>
      <td name="date"> <%= instrument.buy_date %> </td>
      <td> <%= instrument.name %> </td>
    </tr>
     <% end %>
  </tbody>
</table>	
      </div>
    </div>
  </div>

    <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingFive">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive">
        Другие доходы
      </button>
    </h2>
    <div id="panelsStayOpen-collapseFive" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingFive">
      <div class="accordion-body">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Сумма</th>
      <th scope="col">Дата</th>
      <th scope="col">Описание</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @investments.sort_by{ |obj| obj.inv_date }.reverse.each do |inv|%>
    <tr>
      <th scope="row"><%= inv.id %></th>
      <td style="color: green" name="+money"> +<%= inv.size %> zl </td>
      <td name="date"> <%= inv.inv_date %> </td>
      <td> <%= inv.description %> </td>
    </tr>
     <% end %>
  </tbody>
</table>	
      </div>
    </div>
  </div>

    <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingSix">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSix" aria-expanded="false" aria-controls="panelsStayOpen-collapseSix">
        Другие расходы
      </button>
    </h2>
    <div id="panelsStayOpen-collapseSix" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingSix">
      <div class="accordion-body">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Сумма</th>
      <th scope="col">Дата</th>
      <th scope="col">Описание</th>
    </tr>
  </thead>
  
  <tbody>
  	<% @rashods[:expenditures].sort_by{ |obj| obj.exp_date }.reverse.each do |exp|%>
    <tr>
      <th scope="row"><%= exp.id %></th>
      <td style="color: red" name="money"> -<%= exp.price %> zl </td>
      <td name="date"> <%= exp.exp_date %> </td>
      <td> <%= exp.name %> </td>
    </tr>
     <% end %>
  </tbody>
</table>	
      </div>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 20px;">
	<%= link_to "Добавить другой доход", new_investment_path, class: "btn btn-primary" %>
	<%= link_to "Добавить другой расход", new_expenditure_path, class: "btn btn-primary" %>
</div>

<div style="margin-top: 20px" class="container">
	<h4 class="">Выбрать диапазон отображения записей</h4>
	<input type="date" id="start_diap">
	<input type="date" id="stop_diap">
	<button class="btn btn-primary" onclick="show()">Показать</button>
</div>


<style type="text/css">
	.not-show{
		border: 0;
    	clip: rect(0 0 0 0);
    	height: 1px;
    	margin: -1px;
    	overflow: hidden;
    	padding: 0;
    	position: absolute;
    	white-space: nowrap;
    	width: 1px;
	}
</style>

<script type="text/javascript">
	function costil(str){
		const [year, month, day] = str.value.split('-');
		return new Date(year, month-1, day).getTime() / 1000;
	}

	function costil2(str){
		const [year, month, day] = str.innerHTML.split('-');
		return new Date(year, month-1, day).getTime() / 1000;
	}

	function show() {
		var tds = document.getElementsByName("date");
		var start = document.getElementById("start_diap");
		var stop = document.getElementById("stop_diap");
		var start_date = costil(start);
		var stop_date = costil(stop);
		let elems = [];
		tds.forEach((elem) => {
			if(costil2(elem) <= start_date || costil2(elem) >= stop_date) {
				elem.parentElement.classList.add("not-show");
				
			} else {
				elems.push(elem.parentElement);
			}
		})
		var babos = 0;
		elems.forEach((elem) => {
			var ndList = elem.childNodes
			var value = ndList[3].innerHTML
			if(value.includes('-')){
				value = value.replace(/[^0-9]/g,"");
				babos -= value;
			} else {
				value = value.replace(/[^0-9]/g,"");
				babos += value;
			}
		})
		var kassa = document.getElementsByName("kassa");
		console.log(kassa);
		kassa[0].innerHTML = babos;
	};
</script>