config/routes.rb
Rails.application.routes.draw do

  get 'index/index'
 

  devise_for :users

    resources :users
    resources :workers
    resources :locations
    resources :instruments
    resources :investments
    resources :expenditures
    resources :salaries
    resources :customers
    resources :work_types
    resources :location_work_types
    resources :location_customers
    resources :diaries
    resources :transports
    resources :materials
    resources :location_materials
    resources :payouts

    root "index#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :location_customers
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :location_work_type
	belongs_to :worker
	belongs_to :salary
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	belongs_to :location
	belongs_to :worker
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :instruments
	has_many :location_customers
	has_many :location_work_types
  	has_many :work_types, through: :location_work_types
  	has_many :location_materials
  	has_many :materials, through: :location_materials
end

app/models/material.rb
class Material < ApplicationRecord
	has_many :location_materials
	has_many :locations, through: :location_materials
end

app/models/payout.rb
class Payout < ApplicationRecord
	belongs_to :location_work_type
end

app/models/salary.rb
class Salary < ApplicationRecord
	belongs_to :worker
	has_many :diaries
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/work_type.rb
class WorkType < ApplicationRecord
	has_many :location_work_types
	has_many :locations, through: :location_work_types
end

app/models/worker.rb
class Worker < ApplicationRecord
	has_many :instruments
	has_many :salaries
	has_many :diaries
end

app/controllers/work_type_controller.rb
class WorkTypeController < ApplicationController
  def show
  end

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/work_types_controller.rb
class WorkTypesController < ApplicationController
  def show
  end

  def index
    @work_types = WorkType.all
  end

  def new
    @work_type = WorkType.new
  end

  def create
    @work_type = WorkType.new(permit_params)
    @work_type.save
    redirect_to(root_path)
  end

  def delete
  end

  def destroy
  end

  def edit
    @work_type = WorkType.find(params[:id])
  end

  def update
    @work_type = WorkType.find(params[:id])
    @work_type.update(permit_params)
    redirect_to(work_types_path)
  end

  private

  def permit_params
    params.require(:work_type).permit(:name, :dimension)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/payouts_helper.rb
module PayoutsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_types_helper.rb
module WorkTypesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/work_types/create.html.erb
<h1>WorkTypes#create</h1>
<p>Find me in app/views/work_types/create.html.erb</p>

app/views/work_types/delete.html.erb
<h1>WorkTypes#delete</h1>
<p>Find me in app/views/work_types/delete.html.erb</p>

app/views/work_types/destroy.html.erb
<h1>WorkTypes#destroy</h1>
<p>Find me in app/views/work_types/destroy.html.erb</p>

app/views/work_types/edit.html.erb
<h1>Редактировать вид работы</h1>

<%= form_for @work_type do |f| %>
	<%= f.label :name, 'название вида работ', class: "form-label" %>
	<%= f.text_field :name, class: "form-control", default: @work_type.name %>
	<br>
	<%= f.label :dimension, 'В чем измеряется работа', class: "form-label" %>
	<%= f.text_field :dimension, class: "form-control", default: @work_type.dimension %>
	<br>

	<%= f.submit 'Внести изменения', class: "btn btn-primary" %>
<% end %>

app/views/work_types/index.html.erb
<h1>Виды работ <%= link_to "Добавить новый вид работ", new_work_type_path, class: "btn btn-primary" %> </h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название</th>
      <th scope="col">Мера</th>
      <th scope="col">Подробнее</th>
    </tr>
  </thead>
  <tbody>
	<% @work_types.each do |work_type| %>
    <tr>
      <th scope="row"><%= work_type.id %></th>
      <td><%= work_type.name %></td>
      <td><%= work_type.dimension %></td>
      <td><%= link_to "Редактировать", "work_types/#{work_type.id}/edit" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/work_types/new.html.erb
<h1>Добавление нового вида работ</h1>

<%= form_for @work_type do |f| %>
	<%= f.label :name, 'название вида работ', class: "form-label" %>
	<%= f.text_field :name, class: "form-control" %>
	<br>
	<%= f.label :dimension, 'В чем измеряется работа', class: "form-label" %>
	<%= f.text_field :dimension, class: "form-control" %>
	<br>

	<%= f.submit 'Добавить', class: "btn btn-primary" %>
<% end %>

app/views/work_types/show.html.erb
<h1>WorkTypes#show</h1>
<p>Find me in app/views/work_types/show.html.erb</p>

app/views/work_types/update.html.erb
<h1>WorkTypes#update</h1>
<p>Find me in app/views/work_types/update.html.erb</p>