config/routes.rb
Rails.application.routes.draw do

  get 'index/index'
 

  devise_for :users

    resources :users
    resources :workers
    resources :locations
    resources :instruments
    resources :investments
    resources :expenditures
    resources :salaries
    resources :customers
    resources :work_types
    resources :location_work_types
    resources :location_customers
    resources :diaries
    resources :transports
    resources :materials
    resources :location_materials
    resources :payouts

    root "index#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :location_customers
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :location_work_type
	belongs_to :worker
	belongs_to :salary
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	belongs_to :location
	belongs_to :worker
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :instruments
	has_many :location_customers
	has_many :location_work_types
  	has_many :work_types, through: :location_work_types
  	has_many :location_materials
  	has_many :materials, through: :location_materials
end

app/models/material.rb
class Material < ApplicationRecord
	has_many :location_materials
	has_many :locations, through: :location_materials
end

app/models/payout.rb
class Payout < ApplicationRecord
	belongs_to :location_work_type
end

app/models/salary.rb
class Salary < ApplicationRecord
	belongs_to :worker
	has_many :diaries
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/work_type.rb
class WorkType < ApplicationRecord
	has_many :location_work_types
	has_many :locations, through: :location_work_types
end

app/models/worker.rb
class Worker < ApplicationRecord
	has_many :instruments
	has_many :salaries
	has_many :diaries
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def show
    @instrument = Instrument.find(params[:id])
  end

  def index
    @instruments = Instrument.all
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(permit_params)
    @instrument.save
    redirect_to(root_path)
  end

  def delete
  end

  def destroy
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def update
    @instrument = Instrument.find(params[:id])
    @instrument.update(permit_params)
    redirect_to(instruments_path)
  end

  private

  def permit_params
    params.require(:instrument).permit(:name, :description, :buy_date, :price, :location_id, :worker_id)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/payouts_helper.rb
module PayoutsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/instruments/create.html.erb
<h1>Instruments#create</h1>
<p>Find me in app/views/instruments/create.html.erb</p>

app/views/instruments/delete.html.erb
<h1>Instruments#delete</h1>
<p>Find me in app/views/instruments/delete.html.erb</p>

app/views/instruments/destroy.html.erb
<h1>Instruments#destroy</h1>
<p>Find me in app/views/instruments/destroy.html.erb</p>

app/views/instruments/edit.html.erb
<h1>Редактирование</h1>

<%= form_for @instrument do |f| %>
	<%= f.label :name, 'Название инструмента', class: "form-label" %>
	<%= f.text_field :name, class: "form-control", default: @instrument.name %>
	<br>
	<%= f.label :description, 'Модель', class: "form-label" %>
	<%= f.text_field :description, class: "form-control", default: @instrument.description %>
	<br>
	<%= f.label :buy_date, 'Дата покупки (дд.мм.гггг)', class: "form-label" %>
	<%= f.date_field :buy_date, :id => "datepicker", class: "form-control", default: @instrument.buy_date %>
	<br>
	<%= f.label :price, 'Цена', class: "form-label" %>
	<%= f.text_field :price, class: "form-control", default: @instrument.price %>
	<br>
	<%= f.label :location_id, 'На каком обьекте сейчас?', class: "form-label" %>
	<%= f.select(:location_id, Location.all.collect {|p| [ p.name, p.id ] }, {}, { class: 'form-control' }) %>
	<br>
	<%= f.label :worker_id, 'У какого работника сейчас?', class: "form-label" %>
	<%= f.select(:worker_id, Worker.all.collect {|p| [ p.name, p.id ] }, {}, { class: 'form-control' }) %>
	<br>

	<%= f.submit 'Добавить', class: "btn btn-primary" %>
<% end %>

app/views/instruments/index.html.erb
<h1>Инструменты <%= link_to "Добавить новый инструмент", new_instrument_path, class: "btn btn-primary" %> </h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название</th>
      <th scope="col">Модель</th>
      <th scope="col">Дата покупки</th>
      <th scope="col">Цена</th>
      <th scope="col">Подробнее</th>
    </tr>
  </thead>
  <tbody>
	<% @instruments.each do |instrument| %>
    <tr>
      <th scope="row"><%= instrument.id %></th>
      <td><%= instrument.name %></td>
      <td><%= instrument.description %></td>
      <td><%= instrument.buy_date %></td>
      <td><%= instrument.price %> zl</td>
      <td><%= link_to "Подробнее", "instruments/#{instrument.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/instruments/new.html.erb
<h1>Добавление нового объекта</h1>

<%= form_for @instrument do |f| %>
	<%= f.label :name, 'Название инструмента', class: "form-label" %>
	<%= f.text_field :name, class: "form-control" %>
	<br>
	<%= f.label :description, 'Модель', class: "form-label" %>
	<%= f.text_field :description, class: "form-control" %>
	<br>
	<%= f.label :buy_date, 'Дата покупки (дд.мм.гггг)', class: "form-label" %>
	<%= f.date_field :buy_date, :id => "datepicker", class: "form-control" %>
	<br>
	<%= f.label :price, 'Цена', class: "form-label" %>
	<%= f.text_field :price, class: "form-control" %>
	<br>
	<%= f.label :location_id, 'На каком обьекте сейчас?', class: "form-label" %>
	<%= f.select(:location_id, Location.all.collect {|p| [ p.name, p.id ] }, {}, { class: 'form-control' }) %>
	<br>
	<%= f.label :worker_id, 'У какого работника сейчас?', class: "form-label" %>
	<%= f.select(:worker_id, Worker.all.collect {|p| [ p.name, p.id ] }, {}, { class: 'form-control' }) %>
	<br>

	<%= f.submit 'Добавить', class: "btn btn-primary" %>
<% end %>

app/views/instruments/show.html.erb
<h1>Инструмент <%= @instrument.name %></h1>

<p>Имя: <%= @instrument.name %></p>
<p>Модель: <%= @instrument.description %></p>
<p>Дата покупки: <%= @instrument.buy_date %></p>
<p>Цена: <%= @instrument.price %>zl</p>
<p>На объекте: <%= @instrument.location.name %></p>
<p>У работника: <%= @instrument.worker.name %></p>

<%= link_to "Редактировать", "#{@instrument.id}/edit", class: "btn btn-primary" %>

app/views/instruments/update.html.erb
<h1>Instruments#update</h1>
<p>Find me in app/views/instruments/update.html.erb</p>